spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/sandbox"
    driverClassName: "org.postgresql.Driver"
    password: "mypassword"
    username: "user"
  flyway:
    locations: "classpath:db/migration,classpath:db/local"
    clean-on-validation-error: "true"
    clean-disabled: "false"
  jpa:
    show-sql: false
